### PR TITLE
Feature v0.14.6 randomemailsforletsencrypt

### PR DESCRIPTION
**Pull request by cameronts**
Modified to use random emails in install scripts.

### CODE REVIEW

**Review by 0xdcarns — APPROVED** [review]

**Comment by 0xdcarns** [comment]
@theguy951357 rft, Test by running install script and checking that the email is random

**Review by theguy951357 — APPROVED** [review]
86aa54faed71e500d8482e71cbc7ea91@email.com

**Comment by theguy951357** [comment]
@cameronts @0xdcarns cancel that pass. installation fails with letsencrypt saying the email is invalid in the traefik logs.

time="2022-07-21T17:12:37Z" level=info msg=Register... providerName=http.acme
time="2022-07-21T17:12:37Z" level=error msg="Unable to obtain ACME certificate for domains \"api.nm.143-198-133-27.nip.io\": cannot get ACME client acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:invalidEmail :: Error creating new account :: \"YOUR_EMAIL\" is not a valid e-mail address" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=http.acme routerName=netmaker-api@docker rule="Host(`api.nm.143-198-133-27.nip.io`)"

**Comment by theguy951357** [comment]
@cameronts @0xdcarns cancel the pass. The email is generated, but doesn't populate to the docker-compose file. In install-netmaker.sh There needs to be       sed -i "s/YOUR_EMAIL/$EMAIL/g" /root/docker-compose.yml  below the sed call for the master key

**Comment by cameronts** [comment]
> @cameronts @0xdcarns cancel the pass. The email is generated, but doesn't populate to the docker-compose file. In install-netmaker.sh There needs to be sed -i "s/YOUR_EMAIL/$EMAIL/g" /root/docker-compose.yml below the sed call for the master key

@theguy951357 @0xdcarns updated and committed/pushed, please see updated script.

**Review by 0xdcarns — APPROVED** [review]

**Review by mattkasun — APPROVED** [review]

**Comment by theguy951357** [comment]
a random email is generated and applied to the docker-compose. pass

**Pull request merged**
