### PR TITLE
add provision for freebsd egress and ingress gateway

### PR DESCRIPTION
**Pull request by alphadose**
## Checklist before requesting a review
- [x] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [x] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [x] Netmaker is awesome.

### CODE REVIEW

**Comment by theguy951357** [comment]
kitemaker ticket 1108 was moved to backlog due to other tasks taking priority and more work is needed. will test if kitemaker ticket is back in needs testing.

**Review by mattkasun — APPROVED** [review]

**Comment by theguy951357** [comment]
notes on GRA-1108

**Comment by theguy951357** [comment]
I cannot register any clients to the server on this one. might need a rebase.

**Comment by afeiszli** [comment]
Converting to draft until we determine what to do with this PR.

**Pull request closed without merging**
