### PR TITLE
fixing nm scripts, adding back interactive script

### PR DESCRIPTION
**Pull request by afeiszli**

### CODE REVIEW

**Comment by theguy951357** [comment]
in the nm-quick-interactive.sh, do we want to use the random email for a default or stay with fake@email.com?

**Comment by afeiszli** [comment]
Good point, I'll add a commit for that

**Review by mattkasun — APPROVED** [review]

**Comment by 0xdcarns** [comment]
> Good point, I'll add a commit for that

are we still waiting on this commit?

**Comment by afeiszli** [comment]
added random email

**Review by 0xdcarns — APPROVED** [review]

**Comment by 0xdcarns** [comment]
@theguy951357 rft

**Comment by theguy951357** [comment]
in nm-quick-interactive.sh, I am getting the following errors in the mesh and VPN setup
configuring netmaker server as ingress gateway
jq: error (at <stdin>:1): Cannot index object with number
creating vpn network (10.201.0.0/16)
configuring netmaker server as vpn inlet...
jq: error (at <stdin>:1): Cannot index object with number

**Comment by afeiszli** [comment]
@theguy951357 I'm unable to replicate this issue, though have submitted a couple updates to the script that may help.

**Review by theguy951357 — APPROVED** [review]
pass

**Pull request merged**
