### PR TITLE
remote ps args, add dirctories

### PR DESCRIPTION
**Pull request by sbilly**
1. remove the -e arg for ps, which openwrt do not supported by default
2. add directories which are required by netmaker in source code.

### CODE REVIEW

**Comment by mattkasun** [comment]
updated the target of this PR to gravitl:develop vice master

**Comment by mattkasun** [comment]
updated the target of this PR to gravitl:develop vice master

**Comment by afeiszli** [comment]
@sbilly this one looks the same as your other PR, which one should we keep?

**Review by afeiszli — CHANGES_REQUESTED** [review]
@sbilly I'm guessing this PR should be closed, and the other one should remain open?

**Comment by afeiszli** [comment]
Have not heard a response in over 1 month, closing this PR. Feel free to re-submit with updates.

**Pull request closed without merging**
