### PR TITLE
add Cli parameter

### LINKED ISSUE #600: Cli missing 'grpcssl' parameter
Cli missing 'grpcssl' parameter

### PR DESCRIPTION
**Pull request by louis-zhou**
resolved #600

### CODE REVIEW

**Comment by afeiszli** [comment]
@louis-zhou thank you for your contribution! Please sign the CLA and we can merge this.

**Comment by afeiszli** [comment]
@louis-zhou we will need an update here or will have to close the PR

**Review by afeiszli — CHANGES_REQUESTED** [review]
@louis-zhou thank you for your contribution! Please sign the CLA and we can merge this.

**Review by louis-zhou — COMMENTED** [review]
resolved #600

**Pull request closed without merging**
