### PR TITLE
Docker compose remove host binding for Caddy

### PR DESCRIPTION
**Pull request by Belphemur**
Hi,

It's better to avoid using `network_mode: host` as much as possible.
If you need it for binding privliedge port like `80` and `443` then it's better to use `capabilities: cap_net_bind_service`.

I'm currently running this config without any issue, caddy is listening on the right ports and we can remove unneeded port bindings by relying on the links

### CODE REVIEW

**Comment by afeiszli** [comment]
Hi @Belphemur, to run netmaker with host networking off, you can use the "contained" compose file: https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.contained.yml

This was actually the main compose file until we hotfixed 0.8.5 last night. Reason being: a lot of people are using the server as a bastion for testing connections and SSH'ing to other machines. This is not feasible without host networking on.

**Comment by Belphemur** [comment]
@afeiszli Hooo I see. That is definitely a usecase for it (I was actually in the middle of installer teleport on a node for that reason).

I'll update the PR to reenable the host network for netmaker. The rest still apply though, Caddy doesn't need it :)

**Comment by Belphemur** [comment]
There is one issue with the current version of the docker-compose file, the network devices created by netmaker don't get deleted when the container goes down. So when it goes back up, it complain that the port is already in use.

**Comment by afeiszli** [comment]
Can you open a ticket for that interface issue and we will take a look? I am aware of it but it will draw attention so we can prioritize. I think all we need to do is just run a delete/recreate if it already exists.

**Comment by afeiszli** [comment]
These changes look good, thank you.

**Comment by Belphemur** [comment]
@afeiszli No problem.

issue created: https://github.com/gravitl/netmaker/issues/440

**Comment by afeiszli** [comment]
@Belphemur I just reverted these changes in develop. The changes to caddyfile + docker-compose cause a CORS issue, and the UI cannot connect with the backend. Will review later but don't want to have them in develop until we figure out a fix.

**Pull request merged**
