### PR TITLE
Workflow signcode

### PR DESCRIPTION
**Pull request by cameronts**

### CODE REVIEW

**Review by mattkasun — APPROVED** [review]

**Review by afeiszli — APPROVED** [review]

**Comment by afeiszli** [comment]
Did you test if the signed binary works? In particular, the current workflow produces a binary that doesn't have a version tag. Can you please test if this generates a functioning binary with the appropriate version tag?

**Comment by cameronts** [comment]
> Did you test if the signed binary works? In particular, the current workflow produces a binary that doesn't have a version tag. Can you please test if this generates a functioning binary with the appropriate version tag?

Yes, updating version number handling

**Comment by cameronts** [comment]
Put to draft while working more on comments.

**Comment by afeiszli** [comment]
@cameronts this is still in draft, should it be marked ready for review?

**Pull request closed without merging**
