### PR TITLE
remote ps args, add dirctories

### PR DESCRIPTION
**Pull request by sbilly**
1. remove the -e arg for ps, which openwrt do not supported by default
2. add directories which are required by netmaker in source code.

### CODE REVIEW

**Comment by mattkasun** [comment]
updated the target of this PR to gravitl:develop vice master

**Comment by afeiszli** [comment]
Thanks @sbilly! , please sign the cla and we will merge.

**Comment by afeiszli** [comment]
@sbilly this patch looks the same as the other PR. Which one should we keep?

**Comment by afeiszli** [comment]
Have not heard a response in over 1 month, closing this PR. Feel free to re-submit with updates.

**Pull request closed without merging**
