### PR TITLE
adding a connect disconnect button

### PR DESCRIPTION
**Pull request by Noexperience-Team**

### CODE REVIEW

**Comment by mattkasun** [comment]
duplicate of PR [619](https://github.com/gravitl/netmaker/pull/1619)

**Comment by Noexperience-Team** [comment]
hello @mattkasun this is not a duplication i had passed the first pr but the workflow had rejected the first one because of a mistake i fixed that mistake and make a new PR

**Comment by mattkasun** [comment]
duplicate of PR [619](url)

> 

if you push to your original branch it will update the other PR

**Comment by Noexperience-Team** [comment]
i didn't know that so you are aaccepting the first one ??

**Pull request closed without merging**
