### PR TITLE
openwrt: mipsle version

### PR DESCRIPTION
**Pull request by oycol**
the service is  base on /bin/bash, if it is necessary i have a version with /bin/sh,some different .

### CODE REVIEW

**Comment by oycol** [comment]
**The binary works well with  https://openwrt.org/toh/lenovo/newifi_d2**

**Soc under test**:   MediaTek MT7621AT

**Requirement**:  wireguard

 <html>
<body>
<!DOCTYPE html>

device under test | fireware | comment
-- | -- | --
NEW_D2 （新三） | ImmortalWrt 18.06 | Compatible with openwrt
Xiaomi CR6608 | ImmortalWrt 18.06 | Compatible with openwrt


</body>
</html>

**Comment by oycol** [comment]
😃

**Comment by afeiszli** [comment]
@oycol not sure if you saw my comment in the code, but I have concerns about the copyright in openwrt-daemon.sh. Did you get this file from somewhere?

**Comment by oycol** [comment]
oh , I forgot to change it, it's an example form this, https://openwrt.org/docs/techref/initscripts#example_init_script,  it's my problem.

**Comment by oycol** [comment]
@afeiszli  hi , I have fix it and add sh script

**Comment by afeiszli** [comment]
Thanks, merging. We should also put this in the netclient-install script for openwrt

**Pull request merged**
