### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by ndorf**
This is a one-byte change in the README.

### CODE REVIEW

**Review by mattkasun — APPROVED** [review]

**Review by abhishek9686 — APPROVED** [review]

**Comment by ndorf** [comment]
This change is neither copyrightable nor patentable, and therefore cannot be the subject of any licensing agreement.

**Comment by afeiszli** [comment]
@ndorf thank you for the contribution, but we are preparing license changes on the server (good ones, which make the license more permissible) but this requires all contributors to have signed the CLA, otherwise we do not have the rights to do this.

**Comment by ndorf** [comment]
I'm afraid that I cannot sign the CLA, simply because I have not sought permission from my employer regarding this change, nor am I going to do so. Luckily, as already stated, the change is obviously too trivial to be covered by copyright or patent law, so no one, including myself or my employer, could plausibly claim any kind of ownership rights over it.

**Comment by ndorf** [comment]
Starting tomorrow, I will be offline and unreachable for up to two weeks. I would just like to say that I have no objection to any solution you might come up with in the meantime. If you want to say that you reverse-engineered this in a clean room, I am happy to take your word for it.

**Comment by abhishek9686** [comment]
has been addressed already

**Pull request closed without merging**
