### PR TITLE
Upgrade Script Updates

### PR DESCRIPTION
**Pull request by afeiszli**

### CODE REVIEW

**Comment by afeiszli** [comment]
- nmctl is currently not working correctly, blocking completion
-  also need to implement Egress

**Comment by afeiszli** [comment]
Upgrade script now functional. Test Steps
1. Create a 0.17.1 server with nm-quick
2. Create a few networks
3. Add a node besides server node
4. Set server node as an Ingress, Egress, and Relay in various configurations
5. Run upgrade script
6. See that node is created on host and retains settings
7. Re-run this test with Netmaker EE

LIMITATIONS:
1. Cannot currently retain private IP address due to bug in nmctl (GRA-1256)
2. Cannot retain a Relay node due to move from node to host (server is getting updated before all nodes, so there are no hosts for it to relay)
3. Cannot retain ext clients

**Comment by afeiszli** [comment]
Note: LATEST tag is on 0.18.1 for testing. Won't work until release is out for current version. Will need to be changed to actual latest upon release.

**Comment by afeiszli** [comment]
@theguy951357 readt for retest

**Review by theguy951357 — APPROVED** [review]
server upgrades with new client replacement for netmaker-1
pass

**Review by 0xdcarns — APPROVED** [review]

**Pull request merged**
