### PR TITLE
Gra 1054/egress route manager

### PR DESCRIPTION
**Pull request by abhishek9686**
refer PR https://github.com/gravitl/netclient/pull/184 for testing steps

### CODE REVIEW

**Review by 0xdcarns — APPROVED** [review]

**Comment by 0xdcarns** [comment]
static checks need addressing (except ncutils ones) @abhishek9686

**Review by mattkasun — CHANGES_REQUESTED** [review]
fix failing integration tests

**Comment by theguy951357** [comment]
will wait on chyanges

**Review by mattkasun — CHANGES_REQUESTED** [review]
fix staticchecks failures

**Review by Aceix — APPROVED** [review]

**Comment by theguy951357** [comment]
setup branches on server and nodes.
joined ubuntuQA and fedoraQA.
initial pings to eachother work.
made an egress gateway on ubuntuQA with VPC range 10.116.0.0/20
should be able to ping rockylinuxQA on same network with a vpc on 10.116.0.13
fedoraQA cannot ping 10.116.0.13

**Review by mattkasun — APPROVED** [review]

**Review by theguy951357 — APPROVED** [review]
egress range is reachable.
interfaces loook normal.
ext clients can ping egress range.
pass

**Pull request merged**
